---
- name: Añadiendo el grupo primario
  group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Añadiendo grupos secundarios
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Configurar usuarios
  include_tasks: manage_user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user

- name: Eliminando usuarios
  user:
    name: "{{ item.username if item.username is defined else item }}"
    state: absent
    remove: "{{ item.remove if item.remove is defined else omit }}"
  with_items: "{{ users_remove }}"
