---
- name: Enable EPEL Repository on AlmaLinux
  dnf:
    name: epel-release
    state: latest

- name: Updating AlmaLinux packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes
  register: upgrade
  tags: upgrade

- name: Reboot server after install packages 
  reboot:

