---
- hosts: web
  tasks:
    - name: Instalar apache
      yum: name=httpd state=latest
    - name: Instalar Samba
      yum:
        name: samba
        state: latest
    - name: Iniciando Servicios
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - httpd
        - smb
    - name: Abriendo firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: copiando contenido
      copy:
        content: "Bienvenido a mi web"
        dest: /var/www/html/index.html
        mode: 0644
    - name: Modificando index
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^Bienvenido'
        line: 'SELINUX=enforcing'
    - name: Modificamos más el text
      lineinfile:
        path: /var/www/html/index.html
        insertbefore: '^SELINUX'
        line: 'Bienvenido a mi servidor web, perro'
...
