---
- hosts: web
  vars:
    - package: samba
    - service: smb
  tasks:
    - name: Instalar {{ package }}
      yum:
        name: "{{ package }}"
        state: latest
    - name: Iniciando {{ service }}
      service:
        name: "{{ service }}"
        state: started
        enabled: true
...
